<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>江南职高聊天室</title>
</head>

<frameset rows="56,*" framespacing="1" border="1" frameborder="1">
<frame name="top" noresize scrolling="no" src="top.htm">
<frameset cols="160,*">

<frame name="left" src="userlogin.asp" scrolling="auto">
<frame name="right" noresize src="cjdisp1.htm">
</frameset>
</frameset>

</html>