<%@language=vbscript %>
<%session("kshm")=""
  session("sm")=""
  %>
<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>欢迎进入</title>
</head>

<body bgcolor="#D6CEFF">
<p>　</p>
<p>　</p>
<center>
<table border="1" width="72%" height="111">
  <tr>
    <td width="100%" colspan="3" height="1" bgcolor="#88CA00">
      <p align="center"><font color="#FF0000" size="6" face="隶书">欢迎进入</font></td>
  </tr>
  <tr>
    <td width="100%" colspan="3" height="1">
      <p align="center"><font color="#000000" size="6" face="隶书">江  
南 职 高 考 试 系 统</font></td> 
  </tr> 
  <tr> 
    <td width="42%" height="31"> 
      <p align="right"><font size="5" face="方正舒体"><a href="login1.asp?teacher=input"><font color="#FF0000">教师出题</font></a></font></td>
    <td width="17%" height="60" rowspan="2">
      <p align="center"><font color="#003366">&lt;</font><font color="#FF0000">&gt;</font></td>
    <td width="41%" height="31"><font size="5" face="华文行楷"><a href="stuanswer.asp"><font color="#003366">学生答题</font></a></font></td>
  </tr>
  <tr>
    <td width="42%" height="29">
      <p align="right"><font size="5" face="方正舒体"><a href="login1.asp?teacher=modify"><font color="#FF0000">教师改卷</font></a></font></td>
    <td width="41%" height="29"><font size="5" face="华文行楷"><a href="cxxt.asp"><font color="#003366">查询系统</font></a></font></td>
  </tr>
  <tr>
    <td width="100%" height="38" colspan="3">
      <p align="center"><font size="4" face="华文琥珀" color="#CCCC00"><a href="index.htm">返 回 到 首 页</a></font></td>
  </tr>
</table>
</center> 
</body> 
 
</html> 
