<html>


<body  bgcolor="navy">
<center>
<img src="jnzg.gif">
</center>
<form method="post" action="chatroom.asp">
<p><font color="#fffff"><b>请输入您的名字:
<input type="text" name="username" size="20">
</b></font></p>
<p><b><font color="#ffffff">请输入您的颜色:
<select name="usercolor">
<option value="shite" style="background=white" selected>白色</option>
<option value="pink" style="background=pink">粉红色</option>
<option value="yellow" style="background=yellow">黄色</option>
<option value="plum" style="background=plum">紫红色</option>
<option value="cyan" style="background=cyan">粉蓝色</option>
<option value="lime" style="background=lime">萤光绿色</option>
</select>
</font></b></p>
<p><b><font color="#ffffff">请选择您的图案:</font></b>
<input type="radio" name="userfig" value="1.gif" checked><img src="1.gif">
<input type="radio" name="userfig" value="2.gif" ><img src="2.gif">
<input type="radio" name="userfig" value="3.gif" ><img src="3.gif">
<input type="radio" name="userfig" value="4.gif" ><img src="4.gif">
<input type="radio" name="userfig" value="5.gif" ><img src="5.gif">
</p><input type="submit" value="登录">
<input type="reset" value="重新输入">
</form>


</body>

</html>
