<!--#INCLUDE FILE="conn.asp" -->
<% dim sj,x1,x2,x3
sj=cint(application("kssj"))*60
x1=request.form("xm")
x2=request.form("xh")
x3=request.form("bj")
%>
<SCRIPT language=JavaScript>                                                                                                                                                                                               
var b,s,x,y
y=<%=sj%>                                                                         
function time(){                                                                                                       
 y--
 b=y
 s=Math.floor(b/60)
 b=b%60
 x=Math.floor(s/60)
 s=s%60
 if(s<10)
 s="0"+s;
  if(b<10)
 b="0"+b;
  if(x<10)
 x="0"+x
 x=" "+x+":"+s+":"+b
 myform.bj1.value=x
if(y==300||y==120||y==30)
alert("时间快到了，赶快交卷！");

if(y==0){
alert("由于未按时交卷，试卷做废！...");
history.back();
}
setTimeout("time()",1000);                                                                                                 
 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
</SCRIPT>           
<SCRIPT language=JavaScript>
var currentpos,timer;

function initialize()
{
timer=setInterval("scrollwindow()",80);
}
function sc(){
clearInterval(timer);
}
function scrollwindow()
{
currentpos=document.body.scrollTop;
window.scroll(0,++currentpos);
if (currentpos != document.body.scrollTop)
sc();
}
document.onmousedown=sc
document.ondblclick=initialize
</script>

<html>
<%dim exec,dh,tx,diff,diff1,diff2,diff3,ts,na,m,sm, kssj,xm,xh,bj
   exec=application("exec") 
   sm=application("sm")
   dh=application("dh")
   kssj=application("kssj")
'set conn=server.createobject("adodb.connection")  
 
'conn.open "dsn=xiong1"  
set rs=server.createobject("adodb.recordset") 
session("exec")=exec 
rs.open exec,conn,3,3 
%>
<center>
<body>
<form method="post" action="sjda.asp"  name="myform"> 
<span style="background-color: #FFFF00"><font face="楷体_GB2312" color="#0000FF" size="5"><%=application("sm")%></font></span> 
<p>
姓名：<input type="text" name="xm" size="8" maxlength="12" value="<%=x1%>">&nbsp; 学号：                           
<input type="text" name="xh" size="8" maxlength="12" value="<%=x2%>">&nbsp; 班级：                              
<input type="text" name="bj" size="10" maxlength="12" value="<%=x3%>">                              
&nbsp;                                     
</p>                                                           
<p>                         
考试时间:<%=kssj%>分钟&nbsp;&nbsp; 倒计时： <input align="center" type="text" name="bj1" size="10" maxlength="12">                              
<SCRIPT language=JavaScript>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
<!--                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
function showtime(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 if (!document.layers&&!document.all)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 return                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 var Digital=new Date()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 var hours=Digital.getHours()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 var minutes=Digital.getMinutes()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 var seconds=Digital.getSeconds()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 var dn="AM"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 if (hours>12){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 dn="PM"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 hours=hours-12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 if (hours==0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 hours=12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 if (minutes<=9)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 minutes="0"+minutes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 if (seconds<=9)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 seconds="0"+seconds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
//change font size here to your desire                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
myclock="&nbsp"+hours+":"+minutes+":"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 +seconds+" "+dn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
if (document.layers){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
document.layers.liveclock.document.write(myclock)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
document.layers.liveclock.document.close()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
else if (document.all)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
liveclock.innerHTML=myclock                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
setTimeout("showtime()",1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
//-->                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
</SCRIPT>                                                                    
<SPAN id=liveclock style="Z-INDEX: 1"></SPAN>                                                                    
<SCRIPT>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 showtime();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
</SCRIPT>                                  
</p>                                                            
<table align="lift" border="1" width="100%">                                                               
<%tx=""                                                               
 ts=0                                                               
%>                                                               
  <%do while not rs.eof                                                                           
ts=ts+1                                                               
if tx<>rs("section") then                                                               
 ts=1                                                               
 tx=rs("section")                                                               
 %>                                                               
 <tr align="center" bgColor="#666699" ><td  width="100%" colspan="2">                                                               
  <font color="#FFFF00" face="楷体_GB2312" size="5"><%=tx%></font>　</td>                                                               
 </tr>                                                               
 <%end if%>                                                               
 <tr width="100%" > <blockquote><td colspan="2"><%=ts&"."%><%=rs("que")%>　</td>                                                               
 </tr>                                                               
 <%if tx="选择题" then%>                                                               
 <tr align="center"><td width="50%">A:<%=rs("choicea")%></td><td width="%50">B:<%=rs("choiceb")%></td></tr>                                                               
  <tr align="center"><td width="50%">C:<%=rs("choicec")%></td><td width="50%">D:<%=rs("choiced")%></td></tr>                                                               
  <%end if%>                                                               
                                                                 
                                                                 
<%  na=tx&ts %>                                                               
  <tr><td width="100%"  colspan="2" bgColor="#669999">                                                               
<% if tx="选择题"then                                                               
  m="请选择：<input type='radio' name='"+na+"' value='A'> A"%>                                                               
  <%=m%>&nbsp;&nbsp;&nbsp;&nbsp;                                                               
 <% m="<input type='radio' name='"+na+"' value='B'> B"%>                                                               
<%  =m%> &nbsp;&nbsp;&nbsp;&nbsp;                                                              
  <%m="<input type='radio' name='"+na+"' value='C' checked> C"%>                                                               
 <% =m     %>&nbsp;&nbsp;&nbsp;&nbsp;                                                               
<%m="<input type='radio' name='"+na+"' value='D'> D"%>                                                               
 <% =m %>&nbsp;&nbsp;&nbsp;&nbsp;                                                               
  <%else                                                                
  if tx="判断题" then                                                               
  m="正确否：<input type='radio' name='"+na+"' value='yes'  checked>正确"%>                                                               
  <%=m%>&nbsp;&nbsp;&nbsp;&nbsp;                                                               
 <% m="<input type='radio' name='"+na+"' value='no'>错误"%>                                                               
<%  =m%>                                                               
                                                                 
<%else                                                                
  if tx="填空题"  then
  m="答案是：<textarea  name='"+na+"' cols='94' rows='2'></textarea>"
  else
  m="答案是：<textarea  name='"+na+"' cols='94' rows='6'></textarea>"
  end if
  %>                                                               
  <%=m%>                                                               
  <%end if%>                                                               
  <%end if%></td></tr>                                                               
  <%rs.movenext%><%loop%>                                                      
<% rs.close                                                     
 conn.close                    
 %>                  
</table>                                                  
<p><input type="submit" name="submit" value="交&nbsp;&nbsp;卷"></p>
</form>      
<script language=JavaScript>                                                          
time();                  
  </script>                                                             
<p><a href=kh.asp>放弃并返回</a>                                             
<a href=index.htm>回到首页</a></p>                   
</body>
</center>

</html>